---
- hosts: all
  become: True
  vars:
    domain: ec2-3-82-245-95.compute-1.amazonaws.com
  tasks:
    - name: Install apache on ubunt16
      apt: name=apache2 state=latest update_cache=yes
    - name: enable mod_rewrite
      apache2_module: name=rewrite state=present
      notify: 
        - restart apache2
    - name: apache2 listen on port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2
    - name: apache2 virtual host on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - restart apache2
    - name: create VirtualHost file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
     
